name: persistence
description: 用build_runner自动生成基于Hive的key-value存储类
version: 1.0.0
homepage: https://git.sqlce.cn/TreeM/flutter_persistence
publish_to: 'https://git.sqlce.cn/api/packages/TreeM/pub'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  persistence_annotation:
    hosted: 'https://git.sqlce.cn/api/packages/TreeM/pub'
    version: '>=1.0.0 <2.0.0'

  path: ^1.8.3

  source_gen: ^1.4.0
  dart_style: ^2.3.4
  analyzer: ^6.0.0
  build: ^2.4.1

  dartx: ^1.2.0

  recase: ^4.1.0

dev_dependencies:
  pedantic: ^1.11.1
  build_config: "1.1.0"
