name: persistence
description: 用build_runner自动生成基于Hive的key-value存储类
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  persistence_annotation:
    git:
      url: https://github.com/lvsecoto/flutter_persistence.git
      ref: v1
      path: persistence_annotation

  path: ^1.8.3

  source_gen: ^1.4.0
  dart_style: ^2.3.4
  analyzer: ^6.0.0
  build: ^2.4.1

  dartx: ^1.2.0

  recase: ^4.1.0

dev_dependencies:
  pedantic: ^1.11.1
    # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: "1.1.0"
